name: hello_angel
dependencies:
    http: ^0.12.0+2
    angel_auth: ^2.0.0-alpha
    angel_mongo: ^2.0.0
    angel_framework: ^2.0.0
    angel_model: ^1.0.0
    angel_serialize: ^2.0.0
    dotenv: ^1.0.0
dev_dependencies:
    angel_serialize_generator: ^2.0.0
    build_runner: ^1.0.0